config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  # letter_opener用のルーティング
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'home#top'
  get 'home/about' => 'home#about'
  get '/search', to: 'search#search'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books,only: [:index,:show,:create,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # 'favorites'はモデル名ではなくメソッドとして定義している。
  has_many :book_comments, dependent: :destroy

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true


  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得
  # 外部キーの定義
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得
  # 外部キーの定義
  has_many :following_user, through: :follower, source: :followed #自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower #自分をフォローしている人
  # foregin_key = 入口　source = 出口　through: :○○○ = 中間テーブルは○○○
  # follower_id(自分) → follower_id(自分)を目印にfollower(中間テーブル)に入り,
  # followed_id(自分がフォローしている人＝他人)の情報を取得して出てくる。
  # following_userで取得できるのは自分がフォローしている＝他人のデータ

  def follow(user_id)
    follower.create(followed_id: user_id)
    # followed_id:use_idを代入しながらインスタンスを作成
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    super
    if @user.save
      ThanksMailer.send_confirm_to_user(@user).deliver
      # redirect_to @user
    end
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= user.name%></td>
        <td>フォロー数：<%= user.follower.count %></td>
        <td>フォロワー数：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <%if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th><%= link_to user.follower.count, user_follows_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followed.count, user_followers_path(user) %></th>
	</tr>
</table>

<!-- フォローボタン -->
<% if current_user != user %>
	<% if current_user.following?(user) %>
		<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
		<% else %>
			<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
		<% end %>
<% end %>

<% if user == current_user %>
	<div class="row">
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <h2>User info</h2>

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/errors', obj: @user %>

      <div class="field">
      	<%= f.label :name %>
      	<%= f.text_field :name, class: "name" %>
      </div>

      <div class="field">
      	<%= f.label :image %>
      	<%= f.attachment_field :profile_image, class: "user_image" %>
      </div>

      <div class="field">
      	<%= f.label :introduction %>
      	<%= f.text_area :introduction, class: "introduction" %>
      </div>

      <div class="actions">
      	<%= f.submit %>
      </div>

    <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">

    <h2>User info</h2>
    <%= render 'users/profile', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9">
    <h2>Users</h2>
      <%= render 'index',users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">

    <h2>User info</h2>
    <%= render 'users/profile', user: @user %>
    <!--同コントローラーのviewで表示ならusersは省略可 -->

    <h2>New book</h2>
    <%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9">
    <h2>Books</h2>
     <!--books一覧 -->
    <table class="table table-hover table-inverse">
      <thead>
      	<tr>
      		<th></th>
      		<th>Title</th>
      		<th>Opinion</th>
      		<th colspan="3"></th>
      	</tr>
      </thead>

      <tbody>
      	<% @books.each do |book| %>
        	<tr>
        		<td>
        			<%= link_to (book.user) do %>
        			<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
        			<% end %>
        		</td>
        		<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        		<td><%= book.body %></td>
          <!-- コメント数 -->
          <td>
            <%= "コメント数：#{book.book_comments.count}" %>
          </td>
          <!-- ここまで -->
          </tr>
        <% end %>
      </tbody>
    </table>
    <!--books一覧 -->
  </div>
</div>

<!-- google mapの表示 -->
<% if @user == current_user %>
  <h2>Your MAP</h2>
  <div id='map' class="<%= @user.prefecture_code + @user.city + @user.street %>"></div>
<% end %>
<style>
#map{
  height: 400px;
}
</style>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()
  geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 9
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>