config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  # letter_opener用のルーティング
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'home#top'
  get 'home/about' => 'home#about'
  get '/search', to: 'search#search'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books,only: [:index,:show,:create,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  has_many :favorites
  has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
  	@books = Book.find(params[:id])
    @user = @books.user
    @book = Book.new
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    @users = User.all
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id=current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to (book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
    <%= book.user.name %>
  <% end %>
</td>

<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body %></td>

<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart" id="<%= book.id %>"></span>
      <%= book.favorites.count %> いいね
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty" id="<%= book.id %>">
      </span>
      <%= book.favorites.count %> いいね
    <% end %>
  <% end %>
</td>

<!-- コメント数 -->
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_comment.html.erb
<div class="float-wrapper">
  <h2 class="comment-count"><%= book_comments.count %>件のコメント</h2>
</div>
<ol>
  <% book_comments.each do |book_comment| %>
    <li class="comment">
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
            <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <div class="link-author"><%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
            </div>
            <span class="comment-meta">
              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry">
            <%= book_comment.comment %>
          </div>

          <!-- コメント投稿者のみ削除リンク -->
          <% if book_comment.user.id == current_user.id %>
            <%= link_to "削除",book_book_comments_path(book_id: book_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger", remote: true %></td>
          <% end %>
          <!-- ここまで -->

        </div>
      </div>
    </li>
  <% end %>
</ol>

app/views/books/_detail.html.erb
<td>
  <%= link_to (book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
    <%= book.user.name %>
  <% end %>
</td>

<td><%= link_to book.title, books_path %></td>
<td><%= book.body %></td>

<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart" id="<%= book.id %>"></span>
      <%= book.favorites.count %> いいね
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty" id="<%= book.id %>">
      </span>
      <%= book.favorites.count %> いいね
    <% end %>
  <% end %>
</td>

<!-- コメント数 -->
<td>コメント数：<%= book.book_comments.count %></td>

<!-- 投稿者のみ編集,削除ボタン -->
<% if book.user == current_user %>
  <td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
  <td><%= link_to "Destroy",book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %></td>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr class="book_<%= book.id %>">
        <%= render '/books/book', book: book %>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>Editing Book</h1>
    <%= render 'layouts/errors', obj: @book %>

    <%= render "books/newform", book: @book %>
    <%= link_to "Show", @book, class: "book_#{@book.id}" %>
    <%= link_to "Back", books_path, class: "back" %>

  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>
  <div class="row">
  	<div class="col-xs-3">

  		<h2>User info</h2>
  		<%= render 'users/profile', user: current_user %>

  		<h2>New book</h2>
  		<%= render 'books/newform', book: @book %>

  	</div>

  	<div class="col-xs-9">
  		<h2>Books index</h2>

      <%= render 'index', books: @books %>
  	</div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-xs-3">

  	<h2>User info</h2>
  	<%= render 'users/profile', user: @user %>

  	<h2>New book</h2>
  	<%= render 'books/newform', book: @book %>

  </div>

  <div class="col-xs-9">
  	<h2>Book detail</h2>

  	<table class="table">
  		<tr class="book_<%= @books.id %>">
        <%= render 'detail', book: @books %>
  		</tr>
  	</table>

    <!-- コメント一覧 -->
    <div class="comment-list bt style" id="comments_<%= @books.id %>">
      <%= render 'comment', book_comments: @books.book_comments %>
    </div>
    <hr>

    <!-- コメントフォーム -->
    <div class="section-title-wrapper">
      <h3 class="section-title left">
        <span>コメント</span>
      </h3>
    </div>
    <%= form_with model:[@books, @book_comment], data: {remote: true} do |f| %>
      <div class="row">
        <div class="col-xs-12">
          <%= f.text_area :comment, rows:'5', class:"form-control",placeholder:"コメントをここに" %>
        </div>
      </div>
      <%= f.submit "送信する", class:"btn btn-lg pull-right" %>
    <% end %>
    <!-- ここまで -->

  </div>
</div>